### PR TITLE
Add a centered squared logo variant

### PR DESCRIPTION
**Pull request by ForNeVeR**
This _partially_ resolves issue #9.

### CODE REVIEW

**Comment by rexim** [comment]
I changed the title of #9 and now it's completely unrelated to this PR

**Comment by ForNeVeR** [comment]
What a pity!

**Comment by rexim** [comment]
Thanks for the PR! I have a couple of ideas that I'd like to address in the scope of this PR. I'm gonna do that a bit later today.

**Comment by rexim** [comment]
Never mind. LGTM. :+1:

**Review by rexim — APPROVED** [review]

**Comment by ForNeVeR** [comment]
Thanks for the review.

**Pull request merged**
