### PR TITLE
Add a bunch of logo prototypes

### PR DESCRIPTION
**Pull request by rexim**
I had this idea in my head for a pretty long time and only now I found the inspiration to bring it to life. Please review.

cc @codingteam

### CODE REVIEW

**Comment by hagane** [comment]
Looks like a turkic paedo IMO.

**Comment by Minoru** [comment]
CC didn't work—I didn't get any emails about this PR.

Anyway, I find the prototypes creepy. I can't put my finger on what _exactly_ scares me, but… yeah. Creepy.

What happened to a-cat-with-a-cup-of-tea picture you showed us half a year ago? Too complicated for a logo?

**Comment by ForNeVeR** [comment]
Very creepy indeed. I like that!

**Comment by rexim** [comment]
> Anyway, I find the prototypes creepy. I can't put my finger on what exactly scares me, but… yeah. Creepy.

Hm... This is interesting... Probably because the "eyes" are too big. I'll try to see how I can improve that. Thanks!

> What happened to a-cat-with-a-cup-of-tea picture you showed us half a year ago? Too complicated for a logo?

Yes, you are right. It's too complicated for a logo. But he can be a mascot though.

**Comment by rexim** [comment]
Thank you Mr @ForNeVeR ^_^

**Comment by ForNeVeR** [comment]
Okay, we had an agreement with @rexim to merge that now and improve in future.

**Pull request merged**
